all:
	gcc -Ofast -o ../bin/Engine Main.c Init.c Attacks.c IO.c Position.c Data.c MoveGen.c MoveHandler.c Perft.c Utils.c Evaluate.c Search.c UCI.c

debug:
	gcc -o ../bin/EngineDebug Main.c Init.c Attacks.c IO.c Position.c Data.c MoveGen.c MoveHandler.c Perft.c Utils.c Evaluate.c Search.c UCI.c